language: python
python:
  - 2.6
  - 2.7
  - 3.2
  - 3.3
  - pypy
install:
  - python setup.py develop
  - easy_install . jpcw.tools[test]
script:
  - make test -k
after_success:
  - easy_install coveralls
  - coveralls
